apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: longhorn-system
type: Opaque
data:
  # See https://longhorn.io/docs/1.2.4/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-aws-s3-backupstore
  AWS_ACCESS_KEY_ID: {{ .Values.s3.access_key.id | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.access_key.secret | b64enc | quote }}
  AWS_ENDPOINTS: {{ printf "https://%s" .Values.s3.endpoint | b64enc | quote }}
  VIRTUAL_HOSTED_STYLE: dHJ1ZQ== # true
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: "^1"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  timeout: '10m0s' # Account for slow performance of cluster on first setup.
  values:
    {{ .Files.Get "bootstrap-values/longhorn.yaml" | nindent 4 }}
    defaultSettings:
      # See https://longhorn.io/docs/1.2.4/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-aws-s3-backupstore
      backupTarget: {{ printf "s3://%s@%s/" .Values.s3.buckets.backup .Values.s3.region }}
      backupTargetCredentialSecret: s3-secret
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: acme
        external-dns.alpha.kubernetes.io/managed-by: {{ include "cluster_fqn" . }}
        {{ include "admin_auth_annotations" . | nindent 8 }}
      host: {{ include "get_hostname" (dict "service" "longhorn_ui" "context" $) }}
      tls:
        - hosts:
            - {{ include "get_hostname" (dict "service" "longhorn_ui" "context" $) }}
          secretName: longhorn-cert
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-prometheus-servicemonitor
  namespace: longhorn-system
  labels:
    name: longhorn-prometheus-servicemonitor
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  namespaceSelector:
    matchNames:
    - longhorn-system
  endpoints:
    - port: manager
---
# Snapshot cleanup job to avoid too-many-snapshots errors
# See docs here: https://longhorn.io/docs/1.4.1/snapshots-and-backups/scheduling-backups-and-snapshots/#set-up-recurring-jobs-using-a-longhorn-recurringjob
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snap-delete-older-7d
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: '0 0 * * *'
  groups:
    - default
  retain: 7
  task: snapshot-delete
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: longhorn-system
  labels:
    grafana_dashboard: "1"
data:
{{ (.Files.Glob "config/grafana-dashboards/longhorn*").AsConfig | indent 2 }}
