{
 "title": "Kubernetes/Tanzu/Velero",
 "description": "Velero Stats maintained by Velero team",
 "tags": [ "velero" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "schedule",
    "query": {
     "query": "label_values(velero_backup_attempt_total, schedule)"
    }
   },
   {
    "name": "csi_backup_name",
    "query": {
     "query": "label_values(velero_csi_snapshot_attempt_total, backupName)"
    }
   },
   {
    "name": "restic_node",
    "query": {
     "query": "label_values(restic_pod_volume_backup_enqueue_count, node)"
    }
   },
   {
    "name": "restic_backup_name",
    "query": {
     "query": "label_values(restic_restic_operation_latency_seconds_gauge, backupName)"
    }
   },
   {
    "name": "restic_operation",
    "query": {
     "query": "label_values(restic_restic_operation_latency_seconds_gauge, operation)"
    }
   },
   {
    "name": "restic_pvb_name",
    "query": {
     "query": "label_values(restic_restic_operation_latency_seconds_gauge, pod_volume_backup)"
    }
   },
   {
    "name": "fsb_node",
    "query": {
     "query": "label_values(pod_volume_backup_enqueue_count, node)"
    }
   },
   {
    "name": "fsb_backup_name",
    "query": {
     "query": "label_values(pod_volume_operation_latency_seconds_gauge, backupName)"
    }
   },
   {
    "name": "fsb_operation",
    "query": {
     "query": "label_values(pod_volume_operation_latency_seconds_gauge, operation)"
    }
   },
   {
    "name": "fsb_pvb_name",
    "query": {
     "query": "label_values(pod_volume_operation_latency_seconds_gauge, pod_volume_backup)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backup Success Total",
   "type": "stat",
   "description": "The sum of one-off backup and schedule backup success total ",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "velero_backup_total" }
   ]
  },
  {
   "title": "Backup Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_backup_success_total{schedule=~\"$schedule\"}) / sum(velero_backup_attempt_total{schedule=~\"$schedule\"})"
    }
   ]
  },
  {
   "title": "Backup Deletion Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_backup_deletion_success_total{schedule=~\"$schedule\"}) / sum(velero_backup_deletion_attempt_total{schedule=~\"$schedule\"})"
    }
   ]
  },
  {
   "title": "Volume snapshot Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_volume_snapshot_success_total{schedule=~\"$schedule\"}) / sum(velero_volume_snapshot_attempt_total{schedule=~\"$schedule\"})\n"
    }
   ]
  },
  {
   "title": "Hours since last Backup",
   "type": "table-old",
   "description": "for schedule backup use only",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "(time() - velero_backup_last_successful_timestamp{schedule!=\"\"}) / 60 / 60",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Backup per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(velero_backup_success_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup success"
    },
    {
     "expr": "round(sum(increase(velero_backup_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup failure"
    },
    {
     "expr": "round(sum(increase(velero_backup_partial_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup partial failure"
    },
    {
     "expr": "round(sum(increase(velero_backup_deletion_success_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup deletion success"
    },
    {
     "expr": "round(sum(increase(velero_backup_deletion_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup deletion failure"
    },
    {
     "expr": "sum(avg_over_time(velero_backup_items_total{schedule=~\"$schedule\"}[1h]))",
     "legendFormat": "Backup items total"
    },
    {
     "expr": "sum(avg_over_time(velero_backup_items_errors{schedule=~\"$schedule\"}[1h]))",
     "legendFormat": "Backup items errors_total"
    },
    {
     "expr": "round(sum(increase(velero_backup_validation_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup validation failure"
    },
    {
     "expr": "round(sum(increase(velero_volume_snapshot_success_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup volume snapshot success"
    },
    {
     "expr": "round(sum(increase(velero_volume_snapshot_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup volume snapshot failure"
    }
   ]
  },
  {
   "title": "Backup time heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(velero_backup_duration_seconds_bucket{schedule=~\"$schedule\",le!=\"+Inf\"}[1h])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Backup Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(velero_backup_tarball_size_bytes{schedule=~\"$schedule\"}[15m]))",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Restore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Restore Success Total",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "velero_restore_total" }
   ]
  },
  {
   "title": "Restore Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_restore_success_total{schedule=~\"$schedule\"}) / sum(velero_restore_attempt_total{schedule=~\"$schedule\"})"
    }
   ]
  },
  {
   "title": "Restore per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(velero_restore_success_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Restore success"
    },
    {
     "expr": "round(sum(increase(velero_restore_failed_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Restore failure"
    },
    {
     "expr": "round(sum(increase(velero_restore_validation_failed_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Restore validation failure"
    },
    {
     "expr": "round(sum(increase(velero_restore_partial_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Restore partial failure"
    }
   ]
  },
  {
   "title": "CSI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CSI per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(velero_csi_snapshot_attempt_total{schedule=~\"$schedule\", backupName=~\"$csi_backup_name\"}[1h])))",
     "legendFormat": "CSI Snapshot attempt"
    },
    {
     "expr": "round(sum(increase(velero_csi_snapshot_success_total{schedule=~\"$schedule\", backupName=~\"$csi_backup_name\"}[1h])))",
     "legendFormat": "CSI Snapshot success"
    },
    {
     "expr": "round(sum(increase(velero_csi_snapshot_failure_total{schedule=~\"$schedule\", backupName=~\"$csi_backup_name\"}[1h])))",
     "legendFormat": "CSI Snapshot failure"
    }
   ]
  },
  {
   "title": "Restic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Restic Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(restic_pod_volume_backup_dequeue_count{node=~\"$restic_node\"}) / sum(restic_pod_volume_backup_enqueue_count{node=~\"$restic_node\"})"
    }
   ]
  },
  {
   "title": "Restic per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(restic_pod_volume_backup_enqueue_count{node=~\"$restic_node\"}[1h])))",
     "legendFormat": "Restic enqueue"
    },
    {
     "expr": "round(sum(increase(restic_pod_volume_backup_dequeue_count{node=~\"$restic_node\"}[1h])))",
     "legendFormat": "Restic dequeue"
    }
   ]
  },
  {
   "title": "Restic time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(restic_restic_operation_latency_seconds_gauge{backupName=~\"$restic_backup_name\", node=~\"$restic_node\", operation=~\"$restic_operation\", pod_volume_backup=~\"$restic_pvb_name\"}[15m]))",
     "legendFormat": "Avg over time"
    }
   ]
  },
  {
   "title": "File System Backup(for v1.10 and later)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "title": "FSB Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pod_volume_backup_dequeue_count{node=~\"$fsb_node\"}) / sum(pod_volume_backup_enqueue_count{node=~\"$fsb_node\"})"
    }
   ]
  },
  {
   "title": "FSB per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(pod_volume_backup_enqueue_count{node=~\"$fsb_node\"}[1h])))",
     "legendFormat": "FSB enqueue"
    },
    {
     "expr": "round(sum(increase(pod_volume_backup_dequeue_count{node=~\"$fsb_node\"}[1h])))",
     "legendFormat": "FSB dequeue"
    }
   ]
  },
  {
   "title": "FSB time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(pod_volume_operation_latency_seconds_gauge{backupName=~\"$fsb_backup_name\", node=~\"$fsb_node\", operation=~\"$fsb_operation\", pod_volume_backup=~\"$fsb_pvb_name\"}[15m]))",
     "legendFormat": "Avg over time"
    }
   ]
  }
 ]
}