{{- $idpRef := .Values.oidc.issuer_secret }}
{{- $idpUrl := get ((lookup "v1" "Secret" (default .Release.Namespace $idpRef.namespace) $idpRef.name).data) $idpRef.key | b64dec }}
{{- $clientSecretRef := .Values.oidc.client_secret }}
{{- $clientSecret := get ((lookup "v1" "Secret" (default .Release.Namespace $clientSecretRef.namespace) $clientSecretRef.name).data) $clientSecretRef.key | b64dec }}
{{- $passRef := .Values.smtp.password_secret }}
{{- $smtpPassword := get ((lookup "v1" "Secret" (default .Release.Namespace $passRef.namespace) $passRef.name).data) $passRef.key }}
apiVersion: v1
kind: Secret
metadata:
  name: immich-config
type: Opaque
textData:
  immich-config.yaml: |
    notifications:
      smtp:
        enabled: true
        from: {{ .Values.smtp.from_address }}
        replyTo: {{ .Values.smtp.from_address }}
        transport:
          host: {{ .Values.smtp.host }}
          password: "{{ $smtpPassword | b64dec }}"
          port: {{ .Values.smtp.port }}
          secure: true
          username: {{ .Values.smtp.user }}
    oauth:
      enabled: true
      autoLaunch: true
      autoRegister: true
      clientId: {{ .Values.oidc.client_id }}
      clientSecret: "{{ $clientSecret }}"
      issuerUrl: {{ $idpUrl }}
    server:
      externalDomain: {{ .Values.host }}
