host: ""

org:
  name: ""
  default_locale: "en_US"
  tagline: ""
  logo_url: ""

smtp: # For admin notifications
  host: ""
  port: ""
  user: ""
  starttls: false
  password_secret:
    namespace: kube-system
    name: mail-smtp
    key: password
  from_address: ""

admin_email: ""

ingress: true

snapshots:
  enabled: true
  class_name: snap

zone: "" # Specific zone to localize this release to (pods and volumes)
