apiVersion: v1
kind: Namespace
metadata:
  name: cert-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      version: "^1"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  timeout: '10m0s' # Account for slow performance of cluster on first setup.
  values:
    {{ .Files.Get "bootstrap-values/cert-manager.yaml" | nindent 4 }}
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
    # resources: 
    #   limits:
    #     memory: 256Mi
